const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const out=process.env.AGENTX_TEST_ARTIFACTS||process.cwd();
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.AGENTX_CHROME||undefined,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765');
 await page.locator('#password').fill('Demo-only-password-42!');
 await page.locator('#login-form button').click();
 await page.locator('#shell').waitFor({state:'visible'});
 assert.equal(await page.locator('nav a').count(),9);
 const iconColors=await page.locator('nav .nav-icon').evaluateAll(nodes=>nodes.map(n=>getComputedStyle(n).color));assert.equal(new Set(iconColors).size,9);
 assert.equal(await page.locator('.priority-high').count()>0,true);
 await page.screenshot({path:path.join(out,'agent-x-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'+ Aufgabe',exact:true}).click();
 await page.locator('#record-form [name=priority]').selectOption('medium');
 await page.locator('#record-form [name=title]').fill('Browser Test · <script>alert(1)</script>');
 await page.locator('#record-form [name=body]').fill('Nur Tests. Keine privaten Daten.');
 await page.locator('#record-form [name=source]').fill('Browser-Test');
 await page.getByRole('button',{name:'Eintrag speichern',exact:true}).click();
 await page.locator('#editor').waitFor({state:'hidden'});
 await page.reload();await page.locator('#shell').waitFor({state:'visible'});
 await page.locator('#search').fill('Browser Test');
 await page.getByRole('heading',{name:'Browser Test · <script>alert(1)</script>',exact:true}).waitFor();
 assert.equal(await page.locator('#content script').count(),0);
 await page.locator('[data-edit]').first().click();
 assert.equal(await page.locator('#record-form [name=priority]').inputValue(),'medium');
 await page.locator('#record-form [name=title]').fill('Browser Test · bearbeitet');
 await page.getByRole('button',{name:'Eintrag speichern',exact:true}).click();
 await page.getByRole('heading',{name:'Browser Test · bearbeitet',exact:true}).waitFor();
 await page.locator('#search').fill('');
 await page.locator('a[href="#projects"]').click();
 await page.getByRole('heading',{name:'Projects / Ideas',exact:true}).waitFor();
 await page.locator('[data-edit]').filter({hasText:'Lernplan strukturieren'}).first().waitFor();
 assert.match(await page.locator('#content').innerText(),/1 \/ 2 Aufgaben erledigt · 50 %/);
 await page.locator('a[href="#systems"]').click();
 const download=page.waitForEvent('download');await page.locator('#export').click();
 const saved=await download;assert.match(saved.suggestedFilename(),/agent-x-backup/);
 for(const mod of ['lounge','library','economics','health','laboratory','crew']){await page.locator(`a[href="#${mod}"]`).click();await page.waitForTimeout(50);assert(await page.locator('#content h1').isVisible());if(mod!=='crew'){assert.equal(await page.locator('.area-intro').count(),1);}if(['lounge','library','health','laboratory'].includes(mod))await page.screenshot({path:path.join(out,'agent-x-'+mod+'.png'),fullPage:true});}
 await page.locator('nav a[href="#commander"]').click();
 await page.locator('.deck-details summary').waitFor();
 await page.locator('[data-deck-day]').first().click();
 await page.locator('#calendar-dialog').waitFor({state:'visible'});
 await page.locator('#calendar-close').click();
 await page.locator('#upload-document').click();
 await page.locator('#upload-dialog').waitFor({state:'visible'});
 await page.locator('#upload-close').click();
 await page.locator('.deck-details summary').click();
 await page.locator('#question').fill('Welche Fristen stehen an?');
 await page.locator('#ask-form button').click();
 await page.locator('#answer').getByText('Quelle: Isolierte Testfixture',{exact:false}).first().waitFor();
 assert.match(await page.locator('#answer').innerText(),/Quelle: Isolierte Testfixture/);
 await page.locator('.deck-details summary').click();
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>{window.scrollTo(0,0);document.querySelector('#toast').hidden=true});
 await page.waitForTimeout(250);
 assert.equal(await page.locator('aside').isVisible(),false);
 await page.screenshot({path:path.join(out,'agent-x-iphone.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('#menu').click();await page.locator('a[href="#projects"]').click();
 await page.getByRole('heading',{name:'Projects / Ideas',exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('#capture').click();
 assert.equal(await page.locator('#editor').isVisible(),true);
 await page.locator('#close').click();
 await page.locator('#menu').click();await page.locator('#logout').click();
 await page.locator('#login').waitFor({state:'visible'});
 assert.equal(await page.locator('#content').innerText(),'');
 await page.reload();assert.equal(await page.locator('#login').isVisible(),true);
 assert.deepEqual(errors,[]);
 await browser.close();console.log('Browser PASS: login, nine modules, create/edit/reload, search, XSS escaping, real progress, source answers, export, mobile layout/navigation, logout.');
})().catch(e=>{console.error(e);process.exit(1)});
