// Node VM functional tests. Deliberately not a browser/layout certification.
const vm=require('node:vm');const fs=require('node:fs');const assert=require('node:assert/strict');const path=require('node:path');
const nodes=new Map();
function node(selector){if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',textContent:'',hidden:false,value:'',open:false,dataset:{},style:{},listeners:{},classList:{toggle(){return true},remove(){}},addEventListener(type,fn){const prev=this.listeners[type];this.listeners[type]=prev?async(...args)=>{await prev(...args);await fn(...args)}:fn},setAttribute(){},replaceChildren(){this.innerHTML=''},close(){this.open=false},showModal(){this.open=true},focus(){},reset(){},querySelector(){return node(selector+'/button')}});return nodes.get(selector)}
const document={querySelector:node,querySelectorAll:()=>[],createElement:()=>({click(){}})};
let cookies='',exportURL;
const context=vm.createContext({document,location:{hash:''},navigator:{},window:{addEventListener(){}},console,setTimeout,clearTimeout,Date,URL:{createObjectURL(blob){exportURL=blob;return 'blob:example'},revokeObjectURL(){}},Blob,btoa:s=>Buffer.from(s,'binary').toString('base64'),confirm:()=>true,FormData:class{constructor(target){this.data=target.formData}*[Symbol.iterator](){yield*Object.entries(this.data)}},fetch:async(url,options)=>{const response=await fetch('http://127.0.0.1:8765'+url,{...options,headers:{...options.headers,Cookie:cookies}});const cookie=response.headers.get('set-cookie');if(cookie)cookies=cookie.split(';')[0];return response;}});
const evalJS=code=>vm.runInContext(code,context);
const fixture={kind:'task',title:'Frontend Test <script>x</script>',body:'Suchwort Abc321',module:'projects',status:'open',due:'2026-10-04',project_id:'',source:'Frontend-Testfixture',evidence:'review',observed:'2026-10-04',tags:'Test',url:''};
(async()=>{
 vm.runInContext(fs.readFileSync(path.join(__dirname,'../web/app.js'),'utf8'),context);
 await new Promise(r=>setTimeout(r,100));
 await evalJS("(async()=>{const r=await api('/api/login',{method:'POST',body:JSON.stringify({password:'Demo-only-password-42!'})});csrf=r.csrf;await enter()})()");
 assert.equal(node('#shell').hidden,false);
 assert.equal((node('#navigation').innerHTML.match(/href="#/g)||[]).length,9);
 const result=await evalJS(`api('/api/records',{method:'POST',body:${JSON.stringify(JSON.stringify(fixture))}})`);
 await evalJS('refresh()');
 node('#search').value='Abc321';evalJS('render()');
 assert.match(node('#content').innerHTML,/Frontend Test &lt;script&gt;x&lt;\/script&gt;/);
 assert.doesNotMatch(node('#content').innerHTML,/<script>x/);
 assert.match(node('#content').innerHTML,/Frontend-Testfixture/);
 const editor=node('#record-form');editor.formData={id:result.id,...fixture,title:'Frontend · bearbeitet'};editor.querySelector=()=>node('save-button');
 await editor.listeners.submit({preventDefault(){},target:editor});
 await evalJS('refresh()');
 assert.equal(evalJS(`records.find(r=>r.id==='${result.id}').title`),'Frontend · bearbeitet');
 await evalJS("ask('Welche Fristen stehen an?')");assert.match(node('#answer').innerHTML,/Quelle: Frontend-Testfixture/);
 assert.match(evalJS("projectProgress(records.find(r=>r.kind==='project'))"),/1 \/ 2 Aufgaben erledigt · 50 %/);
 for(const view of ['lounge','library','economics','health','laboratory','crew','projects','systems']){context.location.hash='#'+view;node('#search').value='';evalJS('render()');assert.match(node('#content').innerHTML,/<h1>/);}
 assert.match(node('#content').innerHTML,/Nicht eingerichtet/);assert.match(node('#content').innerHTML,/Inaktiv/);
 const bytes=Buffer.from('Quellenstelle FrontendDokument321');
 node('#document-file').files=[{name:'frontend.txt',size:bytes.length,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)}];
 const uploadForm=node('#upload-form');uploadForm.formData={record_id:'',title:'Frontend Dokument',source:'Dokument-Testfixture',observed:'2026-10-04',project_id:'',tags:'Test'};
 await uploadForm.listeners.submit({preventDefault(){},target:uploadForm});
 assert.equal(evalJS("attachments.filter(d=>d.filename==='frontend.txt').length"),1);
 node('#search').value='FrontendDokument321';evalJS('render()');await new Promise(r=>setTimeout(r,100));
 assert.match(node('#document-results').innerHTML,/Zeile 1/);assert.match(node('#document-results').innerHTML,/Dokument-Testfixture/);
 await evalJS("ask('Was steht über FrontendDokument321 im Dokument?', '#assistant-answer')");
 assert.match(node('#assistant-answer').innerHTML,/Zeile 1/);assert.match(node('#assistant-answer').innerHTML,/Dokument-Testfixture/);
 await node('#open-assistant').listeners.click();assert.equal(node('#assistant-dialog').open,true);
 await node('#assistant-close').listeners.click();assert.equal(node('#assistant-dialog').open,false);
 await node('#content').listeners.click({target:{closest(){return {id:'export',dataset:{}}}}});
 assert.equal(JSON.parse(await exportURL.text()).schema_version,1);
 assert.equal(JSON.parse(await exportURL.text()).documents.length,1);
 const packageData={schema_version:1,records:[{...result,id:'c'.repeat(32),title:'Ergänzter Testeintrag'}]};
 const importInput=node('#import-file');importInput.files=[{size:500,text:async()=>JSON.stringify(packageData)}];
 await importInput.listeners.change({target:importInput});
 assert.equal(evalJS("records.some(r=>r.id==='"+'c'.repeat(32)+"')"),true);
 await importInput.listeners.change({target:importInput});
 assert.equal(evalJS('records.filter(r=>r.id==="'+ 'c'.repeat(32)+'").length'),1);
 assert.equal(evalJS(`records.find(r=>r.id==='${result.id}').title`),'Frontend · bearbeitet');
 const calendarMarkup=evalJS('calendarPanel()');
 const calendarIds=[...calendarMarkup.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(calendarIds).size,calendarIds.length);
 const beforeCalendarFetch=context.fetch;context.fetch=async(url,options)=>url==='/api/calendar/calendars'?{ok:true,json:async()=>({items:[{id:'fixture',summary:'Testkalender',timeZone:'Europe/Berlin'}]})}:beforeCalendarFetch(url,options);
 await node('#content').listeners.click({target:{closest(){return {id:'calendar-list',dataset:{}}}}});
 assert.match(node('#calendar-options').innerHTML,/data-calendar/);assert.match(node('#calendar-options').innerHTML,/Auswahl speichern/);
 assert.doesNotMatch(node('#calendar-list').innerHTML,/data-calendar/);context.fetch=beforeCalendarFetch;
 const health=await evalJS(`api('/api/records',{method:'POST',body:${JSON.stringify(JSON.stringify({...fixture,kind:'event',title:'Health Calendar <unsafe>',module:'health',due:'2026-10-05',body:'Local event'}))}})`);
 const google=await evalJS(`api('/api/records',{method:'POST',body:${JSON.stringify(JSON.stringify({...fixture,kind:'event',title:'Google multi day',module:'lounge',due:'2026-10-05',source:'Google Kalender · Testfixture',body:'Beginn: 2026-10-05\nEnde: 2026-10-07'}))}})`);
 await evalJS('refresh()');evalJS('calendarCursor="2026-10-05";calendarMode="month";calendarArea="all"');
 const month=evalJS('calendarMarkup()');assert.match(month,/Health Calendar &lt;unsafe&gt;/);assert.match(month,/Google multi day/);assert.match(month,/Health/);assert.match(month,/Ganztägig/);assert.doesNotMatch(month,/<unsafe>/);
 assert.equal(evalJS('calendarItems().find(e=>e.r.id==="'+google.id+'").end'),'2026-10-06');
 evalJS('calendarArea="health"');assert.doesNotMatch(evalJS('calendarMarkup()'),/Google multi day/);
 evalJS('calendarArea="all";calendarMode="week"');assert.equal(evalJS('calendarRange()[0]'),'2026-10-05');assert.equal(evalJS('calendarRange()[1]'),'2026-10-11');
 await node('#open-calendar').listeners.click();assert.equal(node('#calendar-dialog').open,true);
 await node('#calendar-dialog').listeners.click({target:{closest(){return {dataset:{calendarNav:'1'}}}}});assert.equal(evalJS('calendarCursor'),'2026-10-12');
 evalJS('calendarCursor="2026-01-31";calendarMode="month"');await node('#calendar-dialog').listeners.click({target:{closest(){return {dataset:{calendarNav:'1'}}}}});assert.equal(evalJS('calendarCursor'),'2026-02-01');
 await node('#calendar-close').listeners.click();assert.equal(node('#calendar-dialog').open,false);
 const timedPayload={...fixture,kind:'event',module:'health',title:'Timed local',due:'2026-10-05',start_time:'09:30',end_time:'10:45',end_date:'2026-10-05'};
 const timed=await evalJS(`(()=>{const d=${JSON.stringify(timedPayload)};applyEventTime(d);return d})()`);
 assert.equal(timed.start_time,undefined);assert.match(timed.body,/^Beginn: /);
 const savedTime=await evalJS(`api('/api/records',{method:'POST',body:${JSON.stringify(JSON.stringify(timed))}})`);
 await evalJS('refresh()');assert.equal(evalJS(`eventTiming(records.find(r=>r.id==='${savedTime.id}')).start_time`),'09:30');
 assert.equal(evalJS(`eventTiming(records.find(r=>r.id==='${savedTime.id}')).end_time`),'10:45');
 assert.throws(()=>evalJS(`applyEventTime(${JSON.stringify({...timedPayload,end_time:'08:00'})})`),/Ende muss nach/);
 assert.throws(()=>evalJS(`applyEventTime(${JSON.stringify({...timedPayload,due:''})})`),/Datum und Start/);

 const oldFetch=context.fetch;context.fetch=async()=>{throw new Error('Disconnected')};
 await assert.rejects(evalJS("api('/api/records')"),/nicht erreichbar/);context.fetch=oldFetch;
 await evalJS(`api('/api/records/${result.id}',{method:'DELETE'})`);
 await node('#logout').listeners.click();
 assert.equal(node('#shell').hidden,true);assert.equal(node('#content').innerHTML,'');
 await assert.rejects(evalJS("api('/api/export')"),/Bitte anmelden/);
 console.log('Frontend PASS: navigation (9), login/API, create, form edit, refresh, search, XSS escaping, sources, real progress, export, additive import/repeat, connection failure, logout. No browser/layout/iOS claim.');
})().catch(e=>{console.error(e);process.exit(1)});
